### ISSUE TITLE
net472 does not show net472 as first choice

### ISSUE THREAD

**Issue by drwill-ms** [joelverhagen/NuGetTools#19]
## Steps

- Visit [link](https://nugettoolsdev.azurewebsites.net/5.5.0-preview.2.6382/framework-precedence?framework=net472&exludedIdentifiers=)
- The first item in the list is net463.
- Also broken for net471, net47, and net48.

## Expected

The framework itself should be listed first.

## Note

When I check with net463, it is it's own first item. My guess is the site isn't fully supporting net47*+ yet.

For the record, your project rocks! Thank you for doing it.

**Comment by joelverhagen** [comment]
Great point. The approach I take to enumerate all frameworks is from reflection magic against the `NuGet.Frameworks` assembly. This is not foolproof because in this particular case `net472` through `net47` are not mentioned at all in the assembly but work as expected (since the rule of "frameworks are backwards compatible" is applied and "net" is a valid framework).

It should be easy enough to both a) include the input framework itself and b) maintain an "include list" of known frameworks that are not mentioned in the NuGet assemblies.

Great catch.

**Comment by joelverhagen** [comment]
I added a hardcoded list of these additional frameworks, instead of doing anything fancy. I'll have it deployed today.
